### ISSUE TITLE
New Allocation for Day Pass is not Created

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#101]
![allocation](https://cloud.githubusercontent.com/assets/186856/10999341/b24343a6-849b-11e5-9d22-32f597940d05.png)

**Comment by freinhard** [comment]
It's not problem with allocations in more then one year. 01.01.2016 - 31.03.2016 is also not working.

![einteilung](https://cloud.githubusercontent.com/assets/186856/11180333/379296a4-8c5a-11e5-82df-83cf7edd6ae6.png)

**Comment by href** [comment]
The problem was the fact that summertime starts on the 27th of March. Sedate didn't handle that right:
https://github.com/seantis/sedate/commit/f0c495a725bf319cec765ae822a1c4843f0788ea
