### ISSUE TITLE
Move Links to Subpages up

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#102]
![links-subpages](https://cloud.githubusercontent.com/assets/186856/11066797/f8351020-87c9-11e5-9b6d-f034a6e94180.png)

**Comment by href** [comment]
Any reason why this was removed from 1.0.0?

**Comment by freinhard** [comment]
I don't remember why it was removed from 1.0.0.

**Comment by href** [comment]
@msom has some reasons that you guys discussed - it being in the right place and all. We'll revisit this for 1.1.0.

**Comment by href** [comment]
This seems to be very much a responsive design issue. If we change this, we move the links above the kontakt/people panel. Currently the links are shown below that.

I would say it does belong above the panel, that is to say this change should be made. Any other opinions?
