### ISSUE TITLE
Show Warning if Lead is Missing

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#103]
Show a warning to logged-in users.

Styling analog to warning below:
![warning](https://cloud.githubusercontent.com/assets/186856/11086389/d55805da-8850-11e5-995c-f5f61da2a6f7.png)

**Comment by freinhard** [comment]
Do we want to add more info to the hit: "Die Einleitung ist wichtig für die Suche und Auflistungen."

![lead](https://cloud.githubusercontent.com/assets/186856/11276981/a8401b24-8ee4-11e5-8ca2-e11dd958d859.png)

**Comment by href** [comment]
-1 I wouldn't add too much text there.

**Comment by freinhard** [comment]
Two phrases and two lines are just fine. See the "hidden" page info box. Also we have to explain what the lead is and why it is important. Seen it in users training.

**Comment by href** [comment]
I contest that the hidden page info box is already too big as well ;)

These things should be hints, not hammers. Think icons instead of big callouts (once the user learns to ignore those, we do not have any way to call out anything to the user anymore).

Just my 50 cent though, not a big deal.

**Comment by href** [comment]
I went for "Diese Seite hat keine Einleitungen. Die Einleitung ist wichtig für die Suche und Auflistungen."
