### ISSUE TITLE
Empty Line Adress Portlet URL Email

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#104]
https://rueti.onegovcloud.ch/themen/kultur-freizeit/kultur/konzert-kollegium-ruti

Is there a reason to add the empty line (paragraph maybe)?

![bildschirmfoto 2015-11-13 um 13 20 33](https://cloud.githubusercontent.com/assets/186856/11145865/790ce66e-8a09-11e5-8fcc-128b6e2a7cdb.png)

**Comment by href** [comment]
If you are referring to the lines not on the picture which are spaced out: Those are paragraphs and they are clearly visible as such in the editor. Remove the empty lines in the editor and they won't show up in the output.

**Comment by freinhard** [comment]
![bildschirmfoto 2015-11-16 um 09 56 30](https://cloud.githubusercontent.com/assets/186856/11177782/603a9564-8c48-11e5-9955-77bd30c4f7d1.png)

**Comment by href** [comment]
I see. That seems to be a css issue. There's only a single `<br>` in there, which is correct. If we can't fix this with css we need to change the markup from:

```html
line
<br>
line
```

To 

```html
<ul>
<li>line</li>
</ul>
```
