### ISSUE TITLE
Partially Reserve Allocations

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#108]
Add the following features:

- [x] Add the ability to create allocations which may be partially reserved.
- [x] Add the ability to reserve parts of an allocation.
- [ ] Add the ability to adjust the time of an existing reservation.
- [x] Show which parts of an allocation are partially reserved.

**Comment by href** [comment]
Everything but the ability to edit an existing reservation is implemented. I'm actually not sure we should even implement editing existing reservations. This would be okay in my mind if we could interact with the person requesting the reservation (say in a comments thread).

We can just send an information that the reservation was changed, but it seems a bit out of the ticket's bounds. So for now the user has to re-open the ticket, deny the reservation and then create a new reservation in it's stead.
