### ISSUE TITLE
Localize Date Form of Date Widget for Input type="date"

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#130]
![safari](https://cloud.githubusercontent.com/assets/186856/11814766/e556927c-a348-11e5-9aa8-0becc6374c71.png)
![chrome](https://cloud.githubusercontent.com/assets/186856/11814767/e588f398-a348-11e5-85e6-61293f84dd3b.png)

**Comment by href** [comment]
Note that the backend expects ISO date, so this should be solved on the frontend.
