### ISSUE TITLE
Option to Disable Date Picker Widget for Date Fields

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#132]
For some fields such as DOB the date widget is rather confusion. Do we want to have the option to disable the widget on the form schema?

**Comment by href** [comment]
If it's confusing the widget should be improved. We can't do this optionally as we would have to add it to the form code syntax (yuck).

**Comment by freinhard** [comment]
> form code syntax (yuck).

Good point! Therefore -1

**Comment by href** [comment]
We should actually do it like in Chrome. There the date input widget is only shown if you click on a button at the right side of the input box. Having it pop up in any case is a bit annoying.

I'm looking into this..

**Comment by href** [comment]
I changed the date picker to behave more like the chrome date picker does. I.E. the date picker is only shown if a button to the right of the input element is clicked:

![screenshot of google chrome 17-12-15 11-26-52](https://cloud.githubusercontent.com/assets/273163/11867466/7377876e-a4b1-11e5-9290-e8c70c2317aa.png)

This button may be used to toggle the date picker. If you don't use the button, the picker is not shown. This is exactly how Chrome does it, which to me is a saner and less obnoxious approach.

**Comment by freinhard** [comment]
👍
