### ISSUE TITLE
Daily Report Email with Key Metrics

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#139]
Send (all) users a daily email (8:00 AM) with the following key metrics:

# Ticket Status
- Open Tickets
- Tickets in Progress
- Closed Tickets (last 24h)

# Visitors & Actions
- Total Visitors (last 24h)
- Top 3 Pages

Do not send the email during the weekend.

**Comment by href** [comment]
The visitors info won't be added for a while. Tickt status has been implemented.
