### ISSUE TITLE
Sort Forms on Title instead of Short Name in Forms Listing

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#140]
![formulare](https://cloud.githubusercontent.com/assets/186856/11935227/05b34a2a-a807-11e5-800b-f66467de7daa.jpg)

Am 21.12.2015 um 16:55 schrieb Baumann Rene <Rene.Baumann@rueti.ch>:

Ich habe in der Liste der Formulare das Formular „Neuer Eintrag im Firmenverzeichnis“ abgeändert in „Gewerbeverzeichnis-Eintrag“ umgetauft. Leider erscheint es jetzt nicht mehr alphabetisch sortiert. Könnte man das automatisieren?

**Comment by href** [comment]
Fixed in 19a86ec
