### ISSUE TITLE
Improve Print Layout Ticket

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#142]
> Wenn man ein Ticket ausdruckt, fehlt auf dem Ausdruck der Formular-Name. D.h. man sieht nicht auf den ersten Blick, um was es überhaupt geht. Könnte man das noch ergänzen auf dem Ausdruck? Gut wäre auch, wenn die Schriftgrösse auf dem Ausdruck verkleinert werden könnte, so dass alles auf einer Seite Platz findet.

**Comment by href** [comment]
The form name is called "Group" and is actually on the print. It just happens to be below the other information. What I can do is move the information above the rest. But it will still be named "Group".
