### ISSUE TITLE
Hide Reservations Link if Allocation is Booked

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#146]
Hide the "Reserve" link if an allocation is booked and not available.

![image001](https://cloud.githubusercontent.com/assets/186856/11973046/0a534522-a955-11e5-8bd3-94e03f06fd46.png)

**Comment by href** [comment]
Instead of hiding we should show a text that it can't be reserved in grey. If we just hide it users might assume that their click does not register.
