### ISSUE TITLE
Link Year News

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#154]
Am 04.01.2016 um 14:55 schrieb Baumann Rene <Rene.Baumann@rueti.ch>:

Guten Tag Herr Reinhard
 
Wenn man auf der Titelseite auf den Link „2015“ unter „Aktuelles“ klickt, kommt fälschlicherweise das Jahr 2016. Könnten Sie das bitte korrigieren?

**Comment by href** [comment]
Doesn't look like 2016 to me:
https://www.duerrenaesch.ch/aktuelles?2015

Cannot reproduce.
