### ISSUE TITLE
Put the People Connected to a Topic into a Separate Tab

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#16]
With a lot of people this gets kind of hard to deal with:
![nachricht_bearbeiten](https://cloud.githubusercontent.com/assets/186856/8544621/0b0b67de-24a7-11e5-8a4d-99e3f24fa064.jpg)

We should implement #19 and then put the people here into separate tabs.

**Comment by href** [comment]
:-1: I personally find nested scrollbars very annoying. If breaks the scrolling flow if your mouse pointer is at the wrong position and it makes it harder to find things by looking.

 I'd like to fix this with separate tabs instead. Contact/People would be separate tabs which could be as long as they like.

**Comment by freinhard** [comment]
+1

**Comment by href** [comment]
See https://github.com/OneGov/onegov.town/issues/19

**Comment by href** [comment]
Maybe this is also an option:
https://select2.github.io/examples.html#multiple

**Comment by href** [comment]
I think we go for putting this in a separate tab.

**Comment by href** [comment]
I tried tabs and I was not happy with it. It adds cognitive load because you have to know where to look.
Nested scrollbars it is.

**Comment by href** [comment]
I'm not too happy with this either. I think for places with *lots* of people we need to rework this concept. Rüti has so many people that it can only be managed if we have some kind of "Add person" widget, showing only people which are actually connected to the page. Throw in some quick javascript based search together with this widget and we are good.
