### ISSUE TITLE
Disable User Account

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#196]
Add a setting to disable a user account. Users with disabled accounts can no longer login.
Do we need to remove the YubiKey from the account since the key will be transferred to a new user.

**Comment by href** [comment]
The latest onegov.user release supports this feature, so it will be in the next town release. The Yubikey doesn't have to be changed, as it simply ignored for inactive users.

**Comment by href** [comment]
This has been implemented for a while.
