### ISSUE TITLE
Reopen a Ticket

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#20]
Accidentally closed tickets. Ticket with a real reason to be reopened.
![bildschirmfoto_2015-07-14_um_18_40_51](https://cloud.githubusercontent.com/assets/186856/8678999/4071c5e2-2a58-11e5-99e6-94fcf2539678.jpg)

**Comment by href** [comment]
This is a good starter task I feel, therefore I shall assign it to @msom.

What needs to be done:

* Add a new method in onegov.ticket.model to reopen.
* The user reopening should be assigned to the ticket.
* Tests for onegov.ticket.model transitions should be added (there are none yet).
* Add the functionality to onegov.town.
* Append this case to the test_tickets testcase.
* Release onegov.ticket
* Push changes of onegov.ticket (no release)

The onegov.ticket release is needed in order for the onegov.town CI to work.

**Comment by href** [comment]
Thought: Do we send another e-mail if the ticket is re-opened? Do we send one, once the ticket is closed for the second time?

**Comment by href** [comment]
So we decided to go with e-mail sending. The latest commit adds notifications for open/close ticket:
https://github.com/OneGov/onegov.town/commit/4a1d84add86adffdd80a176189e510ec15ed0932

All that's left to do is adding notifications for re-opening.

**Comment by href** [comment]
As discussed: We should reopen to the state of 'pending' and open the ticket view directly. 'open' tickets do not have a user assigned to them, so that would make more sense.
