### ISSUE TITLE
iCal Export Time not Correct in Outlook

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#211]
Beim Exportieren von Veranstaltungen stimmen die Zeiten nicht!

![image001](https://cloud.githubusercontent.com/assets/186856/15959695/3dd9832a-2efc-11e6-985d-68ff9c0178cf.jpg)

**Comment by msom** [comment]
It seems that Outlook [does not handle timezones correctly together with daylight saving](http://stackoverflow.com/questions/4006948/ms-outlook-incorrectly-interprets-ics-files-in-local-time-daylight-savings-time):

`DTSTART;TZID=Europe/Zurich;VALUE=DATE-TIME:20160610T200000` 
`DTEND;TZID=Europe/Zurich;VALUE=DATE-TIME:20160610T220000`

Maybe use UTC?

**Comment by msom** [comment]
See https://github.com/OneGov/onegov.event/commit/3a174fafe1acf14664bb960bd02f5134b6e31067

**Comment by href** [comment]
I think a patch release is in order.

**Comment by msom** [comment]
onegov.event==0.4.1
