### ISSUE TITLE
Encoding Emails Apple Mail

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#24]
<img width="654" alt="mail" src="https://cloud.githubusercontent.com/assets/186856/8725691/f347f55a-2bd5-11e5-843e-d5b80260f1c4.png">

**Comment by href** [comment]
Try again please and close the ticket if it works. It works for me now.

**Comment by href** [comment]
Solved with https://github.com/OneGov/onegov.core/commit/0c9c8f3efcc5a472e8c52f786bb31c067fce9bce
