### ISSUE TITLE
Add 'Partner' Logos to Footer

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#267]
z.B. Energiestadt-Logo

![energiestadt](https://user-images.githubusercontent.com/186856/47721298-199cc900-dc50-11e8-95ae-8b6897c94c63.png)

**Comment by freinhard** [comment]
vgl. Partner Logos Feriennet 

![feriennet](https://user-images.githubusercontent.com/186856/47721358-36390100-dc50-11e8-8943-a9d8a043542d.png)

**Comment by freinhard** [comment]
Auch Lauerz möchte zwei Logos im Footer:
- Energiestadt
- Tourismus Region Rigi: https://www.rigi.ch

**Comment by href** [comment]
Logos brauchen einen Link.

**Comment by href** [comment]
Implementiert in https://github.com/OneGov/onegov.org/commit/73ffa53a2bb4bda3d75f5eb298e99f2c68c9bde4
