### ISSUE TITLE
Add Tags to News Atricles

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#268]
Lauerz möchte die Newsartikel mit Tags kategorisieren können. Wahrscheinlich sollten es freie Tags sein. Vorgaben dürften schwierig sein.

- Gemeinderat 
- Gemeindeverwaltung 
- Vereine
- Parteien

**Comment by href** [comment]
Da die News, Themen und alle anderen Seiten die Einleitung und Inhalt haben zusammen unter einem gemeinsamen Interface operieren müssten wir das für alle diese Seiten gleichzeitig implementieren.

Das spricht nicht gegen die Implementation, es scheint mir aber eine Konsequenz zu sein.

**Comment by href** [comment]
Dafür können wir aber eine Tag-Cloud einführen, gleich neben dem 🚧-Sign 😉

**Comment by freinhard** [comment]
Womit das issue hier dokumentiert wäre. Sinnvolle Umsetzung noch offen 🤷🏻‍♂️

**Comment by href** [comment]
Wir machen `#hashtags`

**Comment by freinhard** [comment]
https://govikon.onegovcloud.ch/news/hashtags-in-der-onegov-cloud
