### ISSUE TITLE
Float People List on Mobile

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#271]
![img_20190308_150134_resized_20190308_030335793](https://user-images.githubusercontent.com/186856/54033792-88b59b80-41b5-11e9-82f5-e7f7d706a4fb.jpg)

https://www.lauerz.ch/people

**Comment by href** [comment]
Fixed with https://github.com/OneGov/onegov.org/commit/2a03a7ef3a906bedebf4057f3df9a0e98a65c999
