### ISSUE TITLE
New Archive Links not Working

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#273]
https://www.rueti.ch/news?year=2017?year=2018?year=2016

<img width="1366" alt="Bildschirmfoto 2019-04-25 um 13 22 14" src="https://user-images.githubusercontent.com/186856/56732339-4e9c5b00-675d-11e9-8090-807c88e954b1.png">

**Comment by href** [comment]
Fixed in https://github.com/OneGov/onegov.org/commit/8639478586ea7aca255459cb4960d99e7d749d1c
