### ISSUE TITLE
Display of Available Resources on Calendar View

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#278]
Remove the total number of available resources: "4 verfügbar" instead of "4/6 Verfügbar". 

<img width="1457" alt="Kalender" src="https://user-images.githubusercontent.com/186856/57508640-52ee7980-7302-11e9-9460-9c1534094b26.png">

**Comment by href** [comment]
Implemented in https://github.com/OneGov/onegov.org/commit/c0c992c75086b7611fded08642a43282dccce306
