### ISSUE TITLE
Show Warning on Closing a Ticket without Action

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#279]
Show a warning to the user if a ticket is about to be closed with an excepted action such as:

- Accepting a reservation
- Accepting an publishing an event
- etc.

<img width="1457" alt="Ticket" src="https://user-images.githubusercontent.com/186856/57510643-a1524700-7307-11e9-908d-1079cc10f954.png">

**Comment by href** [comment]
Implemented in https://github.com/OneGov/onegov.org/commit/b9e6de587e6b77f0bee0c8242cd37c3bfcc6ac68
