### ISSUE TITLE
Funktion zu einer Person auf Thema bearbeiten

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#281]
Das Feld zur Eingabe der Funktion einer Person ist nicht mehr sichtbar.

<img width="1370" alt="edit" src="https://user-images.githubusercontent.com/186856/61119457-29390680-a49b-11e9-86bc-de9a4bacbae4.png">

**Comment by href** [comment]
Wurde behoben, auf Lauerz habe ich einen Hotfix ausgerollt, der mit Shift+F5 auf dem Browser geladen werden kann.
