### ISSUE TITLE
Hide the "Except for" Weekdays behind a Default Radio Button

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#35]
Add two option fields and make all weekdays the default. Show the weekdays selection only if the "except for" option is chosen.

![neue_einteilung](https://cloud.githubusercontent.com/assets/186856/9094791/1e6f344e-3bb4-11e5-90df-a69a64f41490.jpg)

**Comment by freinhard** [comment]
Or we make all checkboxes selected and let the user deselect weekdays. But I prefer the first way of doing it.

**Comment by href** [comment]
:+1: For option 1. I don't see a problem implementing that.

**Comment by href** [comment]
I'm going for option two now as it turns out to be much easier ;)

**Comment by href** [comment]
This turns out to be a bit harder than previously thought. We table this for now.
