### ISSUE TITLE
Rework the builtin forms to have the longest choice at the bottom

### ISSUE THREAD

**Issue by href** [OneGov/onegov.town#43]
This is how some forms look today:

```
Delivery * =
    (*) Delivery by Post
         Address = ___
    ( ) Pickup
```
Here the address is only shown if the post option is checked. If one does that, the address pops up below the whole choice block (the only way this is doable). This means that the address is shown after the Pickup option, which is not that nice.

Instead, for choices where only one option has dependencies, we should rewrite the whole thing in a way that puts the option with the dependent choices at the bottom. In the example above, that means rewriting it to this:

```
Delivery * =
    ( ) Pickup
    (*) Delivery by Post
         Address = ___
```

**Comment by freinhard** [comment]
Fields rearranged with [ea82f715]
