### ISSUE TITLE
Person Placeholder Image

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#44]
Make sure the 'local' placeholder image is used an not the one from gravatar.com if an email address is set.

<img width="1388" alt="bildschirmfoto 2015-08-16 um 13 52 25" src="https://cloud.githubusercontent.com/assets/186856/9293130/600ead7c-441e-11e5-9011-ad2f99ba9cc6.png">

**Comment by href** [comment]
:+1:

This might help: http://stackoverflow.com/questions/2103620/gravatar-how-do-i-know-if-a-user-has-a-real-picture

**Comment by href** [comment]
It's a bit of a hackish solution, but it seems to work:
https://github.com/OneGov/onegov.town/commit/4ae199f7976971473dbe08a46edfceed991df0c6

Please do test this with browserstack.

**Comment by href** [comment]
As discussed, gravatar support is no more.
