### ISSUE TITLE
Sort Links in Frontpage Tiles A-Z

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#48]
<img width="689" alt="sort" src="https://cloud.githubusercontent.com/assets/186856/9471306/fdb9bcbe-4b4f-11e5-8996-281ffc706555.png">

**Comment by href** [comment]
I think we have to eventually implement custom ordering (with new elements added in by A-Z). Or add some way to define the links shown on the homepage.

The first 3 children in the order of A-Z of each root page are probably not the most important to show on the homepage.
