### ISSUE TITLE
Add Photo Albums

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#52]
A photo album is a collection of photos. Pictures are uploaded to '/bilder' and then selected for an album. An album has a title and a description.
Links to albums look like this '/album/schulausflug-2015'

**Comment by href** [comment]
Note that this means we have to write our own image plugin for redactor to show the albums there as well.

**Comment by href** [comment]
This also requires some changes in the core, I'd like to integrate something like this and rework the way images are stored:
https://github.com/amol-/depot/blob/master/depot/fields/sqlalchemy.py

**Comment by href** [comment]
Since this means creating database records we need to move all file/image handling out to it's own module.

**Comment by freinhard** [comment]
Also some kind of gallery view is requested. Incl. links to the next image (swipe for mobiles)

**Comment by freinhard** [comment]
http://osvaldas.info/examples/image-lightbox-responsive-touch-friendly/

**Comment by freinhard** [comment]
see #156

**Comment by href** [comment]
Implemented in 925a564e81820dc32f9a51a082b38ab8626c3cd7
