### ISSUE TITLE
Open Link in new Tab

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#53]
Not sure wether we want to support the 'open link in new tab' feature. If not remove the option from the add link overlay.
<img width="1403" alt="link" src="https://cloud.githubusercontent.com/assets/186856/9598646/aa43a0e8-508d-11e5-9ece-1d0e7efdeb17.png">

**Comment by freinhard** [comment]
Am 04.12.2015 um 19:00 schrieb Markus Boos <Gemeindeammann@duerrenaesch.ch>:

Darf ich sie bitten Ticket: https://github.com/OneGov/onegov.town/issues/53
nochmals zu prüfen?
Im Falle von Dateien bin ich nicht damit einverstanden, dass das nicht unterstützt werden soll.

**Comment by href** [comment]
I see the point when it comes to files. Maybe we should open all files in a new tab? Otherwise the result won't be consistent.

**Comment by freinhard** [comment]
+1 for opening files in a new tab. Does the same make sense for external links?

**Comment by href** [comment]
I personally don't like it. With files I see the point because you end up in the PDF viewer or something which is a real context switch. Let's limit this to files for now.
