### ISSUE TITLE
Empty <strong> Tag in Richtext Field Causes Rendering Issue

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#61]
https://duerrenaesch.onegovcloud.ch/themen/gewerbe-tourismus

<img width="1524" alt="strong" src="https://cloud.githubusercontent.com/assets/186856/9688036/19c4b514-532d-11e5-9062-7663612c17f4.png">

**Comment by href** [comment]
I fixed this on the client page. I leave the source for reference:

```html
<p>
    <strong>Fläche Gemeindebann</strong> 591 ha <br>
    davon: <strong>Acker und Wiese</strong> 294 ha, <strong>Wald</strong> 220 ha, <strong>überbaut</strong> 70 ha.<br>
    <strong></strong>
</p>
<p>
    <strong>Geographische Lage des Dorfkerns:<br>
    </strong>08°   09'   östliche Länge<br>47°   19'   nördliche Breite
</p>
<p>
    <strong>Länge Gemeindegrenze:</strong> 13,080 km<br><strong>Länge Dürrenäscher-Weg:</strong> 14,500 km
    <br><strong>Höchste Erhebung:</strong> 766 m ü.M.<br><strong>Tiefster Punkt:</strong> 495 m ü.M.
</p>
```

Note that there are no unclosed tags. Rather, the empty `<strong></strong>` tag seems to cause the issue.

**Comment by freinhard** [comment]
The same goes for empty links.
   <a href="http://www.seantis.ch"></a>

**Comment by msom** [comment]
`<strong></strong>` gets converted to `<strong />` [here](https://github.com/OneGov/onegov.town/blob/master/onegov/town/utils.py#L48).

**Comment by href** [comment]
Do we still need the old code? ;)
