### ISSUE TITLE
Wrong Label for Reservation Form Definition

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#65]
Details -> Definition

<img width="1378" alt="definition" src="https://cloud.githubusercontent.com/assets/186856/9732611/72920a02-5625-11e5-995e-ba2784bfe62b.png">

**Comment by href** [comment]
This was named 'Definition' before, but it was renamed to 'Details' because that's how they are referred to in the ticket.

I guess we should change it to "Form-Definition of Details" or something like it.
