### ISSUE TITLE
Reserve Allocation Context Menu Safari

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#67]
Browser Safari (Mac): Clicking on an allocation to reserve it lets the site jump to the top. It works fine on Firefox and Chrome.

<img width="1334" alt="bildschirmfoto 2015-09-08 um 21 35 24" src="https://cloud.githubusercontent.com/assets/186856/9745417/0c3cf8be-5672-11e5-8db8-0d34f09f86ce.png">
<img width="1334" alt="bildschirmfoto 2015-09-08 um 21 35 29" src="https://cloud.githubusercontent.com/assets/186856/9745419/0f6ea172-5672-11e5-9122-b9aff0e8c757.png">

**Comment by href** [comment]
This has probably something to do with the css animation. Removing it will probably help.
