### ISSUE TITLE
Link Title and Subtitle in Frontpage 'Reservation' Portlet

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#68]
<img width="1175" alt="reservationen" src="https://cloud.githubusercontent.com/assets/186856/9745565/e70f617a-5672-11e5-9ed2-5cf012c9561c.png">

- Change Title to 'Reservationen'
- Change Subtitle to 'Tageskarten und Räume'

**Comment by href** [comment]
You didn't notice that the SBB Tageskarte link on this page was missing? This was a bug.
Can we get rid of this completely?
