### ISSUE TITLE
Add a Way to add Coordinates to Pages/Forms/Ressources etc.

### ISSUE THREAD

**Issue by href** [OneGov/onegov.town#76]
Use leaflet.js and write a content extension.

**Comment by href** [comment]
It might be interesting to use https://www.mapbox.com/ for this.

**Comment by freinhard** [comment]
Geocoding a page and adding a coordinate will add a link to the page leading to a general .../map view. All points of interest (POI) are shown on this page. The current point (link origin) is highlighted (or the other POIs hidden). The map view includes filters to search and select categories of POIs.

**Comment by href** [comment]
This might be useful:
https://github.com/python-visualization/folium

**Comment by href** [comment]
Also this:
https://pypi.python.org/pypi/geocoder

**Comment by href** [comment]
This has been implemented. Improvements as well as the interactive municipality map should go into new tickets if desired.
