### ISSUE TITLE
Display Person as 'Last Name' 'First Name'

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#80]
- [ ] Show the last name before the first name. This also makes the sort oder more obvious.
- [ ] Ad letters to the persons list (see pages A-Z)
- [ ] Adjust the search completion to also use lastname / first name

**Comment by href** [comment]
As a consequence, we have to get rid of the salutation, because "Müller Hans, Dr.", "Müller, Dr. Hans" and so on are weird and no-one of our current users uses this so far.

We can add it back if we have some good use for it.
