### ISSUE TITLE
Move styles to different files

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.town#91]
@href How about splitting up the styles into different files?

**Comment by href** [comment]
Sure, what do you have in mind? A `mixins.scss` is what comes to mind. What else?

**Comment by msom** [comment]
I thought of grouping thematically, e.g. `event.scss`, `ticket.scss` (just for readability)

**Comment by href** [comment]
Okay. Maybe move the smaller stuff into a `shared.scss`.

**Comment by msom** [comment]
Closing this issue, it's not really necessary...
