### ISSUE TITLE
Add the Ability to Sort Items in Person Box Different from A-Z

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#95]
Gemeindeschreiber wants to be on top.

![person](https://cloud.githubusercontent.com/assets/186856/10997504/ed44bee8-848d-11e5-98e2-b76a6d3769ea.png)

**Comment by href** [comment]
This should probably go hand in hand with this ticket:
https://github.com/OneGov/onegov.town/issues/74

**Comment by href** [comment]
Of course we can also implement sorting using the same mechanism as the page sorting to be more consistent.

**Comment by href** [comment]
@freinhard Shouldn't this be part of the 1.0 milestone?
