### ISSUE TITLE
Email Newsletter

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#98]
<img width="732" alt="newsletter" src="https://cloud.githubusercontent.com/assets/186856/10998101/04253764-8493-11e5-9cfd-36c568dde9c0.png">

The email newsletter is periodically (once per month) sent to subscribers. It includes a selection of the latest news and events (!). There is no interface to edit the newsletter.

- Send newsletter with Mailgun
- Add subscribe and unsubscribe forms

**Comment by href** [comment]
This has been implemented and deployed.
